en:
  messages:
    'Login': Login
    'Logout': Logout
    'Forgot your password?': 'Forgot your password?'
    'My Account': 'My Account'
    'Register': Register
  email:
    'Verification required': 'Verification required'
    'Password setting instructions': 'Password setting instructions'
    'Your password was set': 'Your password was set'

de:
  messages:
    'Login': Anmeldung
    'Logout': Ausloggen
    'Forgot your password?': 'Haben Sie Ihr Passwort vergessen?'
    'My Account': 'Mein Konto'
    'Register': Anmelden
  email:
    'Verification required': 'Best√§tigung notwendig'
    'Password setting instructions': 'Passwort-Einstellung Anweisungen'
    'Your password was set': 'Ihr Passwort wurde gesetzt'